//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncClipboard.Core.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncClipboard.Core.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Type 的本地化字符串。
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Account 的本地化字符串。
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add SyncCliboard to application launcher 的本地化字符串。
        /// </summary>
        public static string AddAppImageToUserAppLauncher {
            get {
                return ResourceManager.GetString("AddAppImageToUserAppLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assistant 的本地化字符串。
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates Automatically 的本地化字符串。
        /// </summary>
        public static string AutoCheckUpdates {
            get {
                return ResourceManager.GetString("AutoCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download New Version Automatically 的本地化字符串。
        /// </summary>
        public static string AutoDownloadUpdates {
            get {
                return ResourceManager.GetString("AutoDownloadUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black List 的本地化字符串。
        /// </summary>
        public static string BlackList {
            get {
                return ResourceManager.GetString("BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Download 的本地化字符串。
        /// </summary>
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled 的本地化字符串。
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Test 的本地化字符串。
        /// </summary>
        public static string CancelTest {
            get {
                return ResourceManager.GetString("CancelTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Upload 的本地化字符串。
        /// </summary>
        public static string CancelUpload {
            get {
                return ResourceManager.GetString("CancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create configuration instance, please check if input parameters are correct. 的本地化字符串。
        /// </summary>
        public static string CannotCreateConfigInstance {
            get {
                return ResourceManager.GetString("CannotCreateConfigInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PEM Certificate Key File Path 的本地化字符串。
        /// </summary>
        public static string CertificatePemKeyPath {
            get {
                return ResourceManager.GetString("CertificatePemKeyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PEM Certificate File Path 的本地化字符串。
        /// </summary>
        public static string CertificatePemPath {
            get {
                return ResourceManager.GetString("CertificatePemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This change effects after restart 的本地化字符串。
        /// </summary>
        public static string ChangingLangInfo {
            get {
                return ResourceManager.GetString("ChangingLangInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check and correct input errors before trying again 的本地化字符串。
        /// </summary>
        public static string CheckAndCorrectErrors {
            get {
                return ResourceManager.GetString("CheckAndCorrectErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for updates…… 的本地化字符串。
        /// </summary>
        public static string CheckingUpdate {
            get {
                return ResourceManager.GetString("CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check on the about page 的本地化字符串。
        /// </summary>
        public static string CheckOnAboutPage {
            get {
                return ResourceManager.GetString("CheckOnAboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for Updates for Beta Channel 的本地化字符串。
        /// </summary>
        public static string CheckUpdateForBetaChannel {
            get {
                return ResourceManager.GetString("CheckUpdateForBetaChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All Local History 的本地化字符串。
        /// </summary>
        public static string ClearLocalHistory {
            get {
                return ResourceManager.GetString("ClearLocalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will permanently delete all local history records and cached files on this device. Synced records on the server will not be affected. Continue? 的本地化字符串。
        /// </summary>
        public static string ClearLocalHistoryConfirmMessage {
            get {
                return ResourceManager.GetString("ClearLocalHistoryConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client General 的本地化字符串。
        /// </summary>
        public static string ClientGeneral {
            get {
                return ResourceManager.GetString("ClientGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard file updated 的本地化字符串。
        /// </summary>
        public static string ClipboardFileUpdated {
            get {
                return ResourceManager.GetString("ClipboardFileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string ClipboardHistory {
            get {
                return ResourceManager.GetString("ClipboardHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard image updated 的本地化字符串。
        /// </summary>
        public static string ClipboardImageUpdated {
            get {
                return ResourceManager.GetString("ClipboardImageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string ClipboardSyncing {
            get {
                return ResourceManager.GetString("ClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard text updated 的本地化字符串。
        /// </summary>
        public static string ClipboardTextUpdated {
            get {
                return ResourceManager.GetString("ClipboardTextUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard updated 的本地化字符串。
        /// </summary>
        public static string ClipboardUpdated {
            get {
                return ResourceManager.GetString("ClipboardUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close when losing focus 的本地化字符串。
        /// </summary>
        public static string CloseHistoryWindowWhenLostFocus {
            get {
                return ResourceManager.GetString("CloseHistoryWindowWhenLostFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completely exit 的本地化字符串。
        /// </summary>
        public static string CompletelyExit {
            get {
                return ResourceManager.GetString("CompletelyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config 的本地化字符串。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection Details 的本地化字符串。
        /// </summary>
        public static string ConnectionDetails {
            get {
                return ResourceManager.GetString("ConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item is filtered by content control. Do you want to continue uploading? 的本地化字符串。
        /// </summary>
        public static string ContinueUpload {
            get {
                return ResourceManager.GetString("ContinueUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy And Upload 的本地化字符串。
        /// </summary>
        public static string CopyAndUpload {
            get {
                return ResourceManager.GetString("CopyAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy And Upload without Content Control 的本地化字符串。
        /// </summary>
        public static string CopyAndUploadWithoutFilter {
            get {
                return ResourceManager.GetString("CopyAndUploadWithoutFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy app data folder path to clipboard 的本地化字符串。
        /// </summary>
        public static string CopyAppDataFolderPath {
            get {
                return ResourceManager.GetString("CopyAppDataFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . Current package is &apos;{0}&apos;, please download manually. 的本地化字符串。
        /// </summary>
        public static string CurrentPackageDownloadManually {
            get {
                return ResourceManager.GetString("CurrentPackageDownloadManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The custom configuration file is not used for the username and password 的本地化字符串。
        /// </summary>
        public static string CustomConfigFileDescription {
            get {
                return ResourceManager.GetString("CustomConfigFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/Jeric-X/SyncClipboard/blob/master/docs/README_EN.md#server-configuration 的本地化字符串。
        /// </summary>
        public static string CustomConfigFileLink {
            get {
                return ResourceManager.GetString("CustomConfigFileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Configuration File Path 的本地化字符串。
        /// </summary>
        public static string CustomConfigurationFilePath {
            get {
                return ResourceManager.GetString("CustomConfigurationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Proxy 的本地化字符串。
        /// </summary>
        public static string CustomProxy {
            get {
                return ResourceManager.GetString("CustomProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto detect 的本地化字符串。
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Account 的本地化字符串。
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete account &apos;{0}&apos;?
        ///
        ///This operation cannot be undone. 的本地化字符串。
        /// </summary>
        public static string DeleteAccountConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete record 的本地化字符串。
        /// </summary>
        public static string DeleteHistory {
            get {
                return ResourceManager.GetString("DeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to delete old files on the server when pushing new content 的本地化字符串。
        /// </summary>
        public static string DeletePreviousFilesDescription {
            get {
                return ResourceManager.GetString("DeletePreviousFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete server&apos;s temporary file automatically 的本地化字符串。
        /// </summary>
        public static string DeleteServerTemporaryFileAutoly {
            get {
                return ResourceManager.GetString("DeleteServerTemporaryFileAutoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependencies 的本地化字符串。
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnose 的本地化字符串。
        /// </summary>
        public static string Diagnose {
            get {
                return ResourceManager.GetString("Diagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnose Mode 的本地化字符串。
        /// </summary>
        public static string DiagnoseMode {
            get {
                return ResourceManager.GetString("DiagnoseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t upload files when cutting 的本地化字符串。
        /// </summary>
        public static string DoNotUploadWhenCut {
            get {
                return ResourceManager.GetString("DoNotUploadWhenCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please download and install the icon font manually 的本地化字符串。
        /// </summary>
        public static string DownloadAndInstallIconFont {
            get {
                return ResourceManager.GetString("DownloadAndInstallIconFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download And Paste 的本地化字符串。
        /// </summary>
        public static string DownloadAndPaste {
            get {
                return ResourceManager.GetString("DownloadAndPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        public static string DownloadingFile {
            get {
                return ResourceManager.GetString("DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading web image 的本地化字符串。
        /// </summary>
        public static string DownloadingWebImage {
            get {
                return ResourceManager.GetString("DownloadingWebImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download the Installer 的本地化字符串。
        /// </summary>
        public static string DownloadInstaller {
            get {
                return ResourceManager.GetString("DownloadInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Once Immediately 的本地化字符串。
        /// </summary>
        public static string DownloadOnce {
            get {
                return ResourceManager.GetString("DownloadOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string DownloadPage {
            get {
                return ResourceManager.GetString("DownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Service 的本地化字符串。
        /// </summary>
        public static string DownloadService {
            get {
                return ResourceManager.GetString("DownloadService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading status 的本地化字符串。
        /// </summary>
        public static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Web Image 的本地化字符串。
        /// </summary>
        public static string DownloadWebImage {
            get {
                return ResourceManager.GetString("DownloadWebImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download the original file and copy it after copying a image in browser 的本地化字符串。
        /// </summary>
        public static string DownloadWebImageDescription {
            get {
                return ResourceManager.GetString("DownloadWebImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Account Configuration 的本地化字符串。
        /// </summary>
        public static string EditAccountConfig {
            get {
                return ResourceManager.GetString("EditAccountConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Custom Configuration File 的本地化字符串。
        /// </summary>
        public static string EnableCustomConfigurationFile {
            get {
                return ResourceManager.GetString("EnableCustomConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Downloading 的本地化字符串。
        /// </summary>
        public static string EnableDownload {
            get {
                return ResourceManager.GetString("EnableDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable HTTPS 的本地化字符串。
        /// </summary>
        public static string EnableHttps {
            get {
                return ResourceManager.GetString("EnableHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record local clipboard to history 的本地化字符串。
        /// </summary>
        public static string EnableLocalHistory {
            get {
                return ResourceManager.GetString("EnableLocalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync History 的本地化字符串。
        /// </summary>
        public static string EnableSyncHistory {
            get {
                return ResourceManager.GetString("EnableSyncHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synced records will follow server settings for automatic deletion. 的本地化字符串。
        /// </summary>
        public static string EnableSyncHistoryDescription {
            get {
                return ResourceManager.GetString("EnableSyncHistoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Uploading 的本地化字符串。
        /// </summary>
        public static string EnableUpload {
            get {
                return ResourceManager.GetString("EnableUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Uploading Single File 的本地化字符串。
        /// </summary>
        public static string EnableUploadFile {
            get {
                return ResourceManager.GetString("EnableUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Uploading Multi Files or Folder 的本地化字符串。
        /// </summary>
        public static string EnableUploadMultiFile {
            get {
                return ResourceManager.GetString("EnableUploadMultiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Uploading Text 的本地化字符串。
        /// </summary>
        public static string EnableUploadText {
            get {
                return ResourceManager.GetString("EnableUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Login Failed 的本地化字符串。
        /// </summary>
        public static string FailedToAuth {
            get {
                return ResourceManager.GetString("FailedToAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check update 的本地化字符串。
        /// </summary>
        public static string FailedToCheck {
            get {
                return ResourceManager.GetString("FailedToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download clipboard 的本地化字符串。
        /// </summary>
        public static string FailedToDownloadClipboard {
            get {
                return ResourceManager.GetString("FailedToDownloadClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to set 的本地化字符串。
        /// </summary>
        public static string FailedToSet {
            get {
                return ResourceManager.GetString("FailedToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to set proxy 的本地化字符串。
        /// </summary>
        public static string FailedToSetProxy {
            get {
                return ResourceManager.GetString("FailedToSetProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start server 的本地化字符串。
        /// </summary>
        public static string FailedToStartServer {
            get {
                return ResourceManager.GetString("FailedToStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to Upload:  的本地化字符串。
        /// </summary>
        public static string FailedToUpload {
            get {
                return ResourceManager.GetString("FailedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to parse version from Github 的本地化字符串。
        /// </summary>
        public static string FailToParseVersion {
            get {
                return ResourceManager.GetString("FailToParseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Each file extension per line 的本地化字符串。
        /// </summary>
        public static string FileFilterDescription {
            get {
                return ResourceManager.GetString("FileFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading File Filter 的本地化字符串。
        /// </summary>
        public static string FileSyncFilter {
            get {
                return ResourceManager.GetString("FileSyncFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Mode 的本地化字符串。
        /// </summary>
        public static string FilterMode {
            get {
                return ResourceManager.GetString("FilterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found new version:  的本地化字符串。
        /// </summary>
        public static string FoundNewVersion {
            get {
                return ResourceManager.GetString("FoundNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to About Page 的本地化字符串。
        /// </summary>
        public static string GoToAboutPage {
            get {
                return ResourceManager.GetString("GoToAboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash mismatch 的本地化字符串。
        /// </summary>
        public static string HashMismatch {
            get {
                return ResourceManager.GetString("HashMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Window on Startup 的本地化字符串。
        /// </summary>
        public static string HideOnStartup {
            get {
                return ResourceManager.GetString("HideOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string HistoryFilterAll {
            get {
                return ResourceManager.GetString("HistoryFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string HistoryFilterFile {
            get {
                return ResourceManager.GetString("HistoryFilterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        public static string HistoryFilterImage {
            get {
                return ResourceManager.GetString("HistoryFilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starred 的本地化字符串。
        /// </summary>
        public static string HistoryFilterStarred {
            get {
                return ResourceManager.GetString("HistoryFilterStarred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string HistoryFilterText {
            get {
                return ResourceManager.GetString("HistoryFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transferring 的本地化字符串。
        /// </summary>
        public static string HistoryFilterTransferring {
            get {
                return ResourceManager.GetString("HistoryFilterTransferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Panel 的本地化字符串。
        /// </summary>
        public static string HistoryPanel {
            get {
                return ResourceManager.GetString("HistoryPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can specify the hotkey to open the history panel in the Hotkey settings 的本地化字符串。
        /// </summary>
        public static string HistoryPanelHotkeyDescription {
            get {
                return ResourceManager.GetString("HistoryPanelHotkeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set to 0 to disable time-based cleanup. Only applies to unsynced records. 的本地化字符串。
        /// </summary>
        public static string HistoryRetentionDescription {
            get {
                return ResourceManager.GetString("HistoryRetentionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History retention time (minutes) 的本地化字符串。
        /// </summary>
        public static string HistoryRetentionMinutes {
            get {
                return ResourceManager.GetString("HistoryRetentionMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search text or filename... 的本地化字符串。
        /// </summary>
        public static string HistorySearchPlaceholder {
            get {
                return ResourceManager.GetString("HistorySearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ctrl+F: Focus search box
        ///Ctrl+Home: Scroll to top
        ///Ctrl+End: Scroll to bottom
        ///↑/↓: Navigate items
        ///Tab/Shift+Tab: Switch filters
        ///Enter: Copy and paste
        ///Alt+Enter: Copy only
        ///Esc: Close panel 的本地化字符串。
        /// </summary>
        public static string HistoryWindowKeyboardList {
            get {
                return ResourceManager.GetString("HistoryWindowKeyboardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Shortcuts 的本地化字符串。
        /// </summary>
        public static string HistoryWindowKeyboardShortcuts {
            get {
                return ResourceManager.GetString("HistoryWindowKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single click: Select item
        ///Double click item: Copy to clipboard
        ///Double click image: View full image 的本地化字符串。
        /// </summary>
        public static string HistoryWindowMouseList {
            get {
                return ResourceManager.GetString("HistoryWindowMouseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Operations 的本地化字符串。
        /// </summary>
        public static string HistoryWindowMouseOperations {
            get {
                return ResourceManager.GetString("HistoryWindowMouseOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Panel Operations 的本地化字符串。
        /// </summary>
        public static string HistoryWindowOperations {
            get {
                return ResourceManager.GetString("HistoryWindowOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys 的本地化字符串。
        /// </summary>
        public static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon Missing Detected 的本地化字符串。
        /// </summary>
        public static string IconMissingDetected {
            get {
                return ResourceManager.GetString("IconMissingDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore &quot;Do Not Sync&quot; suggestions in clipboard 的本地化字符串。
        /// </summary>
        public static string IgnoreExcludeForSyncSuggestion {
            get {
                return ResourceManager.GetString("IgnoreExcludeForSyncSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some apps mark sensitive content in clipboard with a suggestion not to sync. Enable this option to ignore that suggestion 的本地化字符串。
        /// </summary>
        public static string IgnoreExcludeForSyncSuggestionDescription {
            get {
                return ResourceManager.GetString("IgnoreExcludeForSyncSuggestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Assistant 的本地化字符串。
        /// </summary>
        public static string ImageAssistant {
            get {
                return ResourceManager.GetString("ImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste image to a textbox directly after copying a image file from file system, and vice versa 的本地化字符串。
        /// </summary>
        public static string ImageAssistantDescription {
            get {
                return ResourceManager.GetString("ImageAssistantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Compatibility 的本地化字符串。
        /// </summary>
        public static string ImageCompatibility {
            get {
                return ResourceManager.GetString("ImageCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the transcoded temporary image file (jpg or gif) after copying a modern image file (heic, webp, etc.) 的本地化字符串。
        /// </summary>
        public static string ImageCompatibilityDescription {
            get {
                return ResourceManager.GetString("ImageCompatibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SyncClipboard is the latest version 的本地化字符串。
        /// </summary>
        public static string ItsLatestVersion {
            get {
                return ResourceManager.GetString("ItsLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest released version 的本地化字符串。
        /// </summary>
        public static string LatestReleasedVersion {
            get {
                return ResourceManager.GetString("LatestReleasedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local version 的本地化字符串。
        /// </summary>
        public static string LocalVersion {
            get {
                return ResourceManager.GetString("LocalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login with Browser 的本地化字符串。
        /// </summary>
        public static string LoginWithBrowser {
            get {
                return ResourceManager.GetString("LoginWithBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log path is null 的本地化字符串。
        /// </summary>
        public static string LogPathNull {
            get {
                return ResourceManager.GetString("LogPathNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Remain Days 的本地化字符串。
        /// </summary>
        public static string LogRemainDays {
            get {
                return ResourceManager.GetString("LogRemainDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max File Size to Upload (MB) 的本地化字符串。
        /// </summary>
        public static string MaxFileSizeToUpload {
            get {
                return ResourceManager.GetString("MaxFileSizeToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Limit 的本地化字符串。
        /// </summary>
        public static string MaxHistoryCount {
            get {
                return ResourceManager.GetString("MaxHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of history records saved by the server 的本地化字符串。
        /// </summary>
        public static string MaxHistoryCountDescription {
            get {
                return ResourceManager.GetString("MaxHistoryCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of records 的本地化字符串。
        /// </summary>
        public static string MaxItemCount {
            get {
                return ResourceManager.GetString("MaxItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only applies to unsynced records. Set to 0 for unlimited records. 的本地化字符串。
        /// </summary>
        public static string MaxItemCountDescription {
            get {
                return ResourceManager.GetString("MaxItemCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version package has been downloaded 的本地化字符串。
        /// </summary>
        public static string NewVersionDownloaded {
            get {
                return ResourceManager.GetString("NewVersionDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find server adapter implementation for this configuration type. Please contact the developer. 的本地化字符串。
        /// </summary>
        public static string NoAdapterFound {
            get {
                return ResourceManager.GetString("NoAdapterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show file sync progress with system notifications 的本地化字符串。
        /// </summary>
        public static string NotifyFileSyncProgress {
            get {
                return ResourceManager.GetString("NotifyFileSyncProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Logged In 的本地化字符串。
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Local Records Only 的本地化字符串。
        /// </summary>
        public static string OnlyShowLocal {
            get {
                return ResourceManager.GetString("OnlyShowLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Config File 的本地化字符串。
        /// </summary>
        public static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open App Data Folder 的本地化字符串。
        /// </summary>
        public static string OpenConfigFileFolder {
            get {
                return ResourceManager.GetString("OpenConfigFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open app data folder in Nautilus 的本地化字符串。
        /// </summary>
        public static string OpenDataFolderInNautilus {
            get {
                return ResourceManager.GetString("OpenDataFolderInNautilus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string OpenDownloadPage {
            get {
                return ResourceManager.GetString("OpenDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show in File Manager 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open History Panel 的本地化字符串。
        /// </summary>
        public static string OpenHistoryPanel {
            get {
                return ResourceManager.GetString("OpenHistoryPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in browser 的本地化字符串。
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Install Folder 的本地化字符串。
        /// </summary>
        public static string OpenInstallFolder {
            get {
                return ResourceManager.GetString("OpenInstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Main UI 的本地化字符串。
        /// </summary>
        public static string OpenMainUI {
            get {
                return ResourceManager.GetString("OpenMainUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to the Update Page 的本地化字符串。
        /// </summary>
        public static string OpenUpdatePage {
            get {
                return ResourceManager.GetString("OpenUpdatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password for logging into the WebDAV server 的本地化字符串。
        /// </summary>
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string PasswordTabRepeat {
            get {
                return ResourceManager.GetString("PasswordTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please add an account 的本地化字符串。
        /// </summary>
        public static string PleaseAddAccount {
            get {
                return ResourceManager.GetString("PleaseAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid value 的本地化字符串。
        /// </summary>
        public static string PleaseEnterValidValue {
            get {
                return ResourceManager.GetString("PleaseEnterValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port range is 1~65535 的本地化字符串。
        /// </summary>
        public static string PortRangeIs {
            get {
                return ResourceManager.GetString("PortRangeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string PortTabRepeat {
            get {
                return ResourceManager.GetString("PortTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing 的本地化字符串。
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program Install Location 的本地化字符串。
        /// </summary>
        public static string PrograminstallLocation {
            get {
                return ResourceManager.GetString("PrograminstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Address 的本地化字符串。
        /// </summary>
        public static string ProxyAddress {
            get {
                return ResourceManager.GetString("ProxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Setting 的本地化字符串。
        /// </summary>
        public static string ProxySetting {
            get {
                return ResourceManager.GetString("ProxySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy Type 的本地化字符串。
        /// </summary>
        public static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Interval (sec) 的本地化字符串。
        /// </summary>
        public static string QueryInterval {
            get {
                return ResourceManager.GetString("QueryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to check for updates 的本地化字符串。
        /// </summary>
        public static string ReadyToCheckUpdate {
            get {
                return ResourceManager.GetString("ReadyToCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Config File 的本地化字符串。
        /// </summary>
        public static string ReloadConfigFile {
            get {
                return ResourceManager.GetString("ReloadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Account 的本地化字符串。
        /// </summary>
        public static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove SyncClipboard from application launcher 的本地化字符串。
        /// </summary>
        public static string RemoveAppImageFromUserAppLauncher {
            get {
                return ResourceManager.GetString("RemoveAppImageFromUserAppLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to Default 的本地化字符串。
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry Times 的本地化字符串。
        /// </summary>
        public static string RetryTimes {
            get {
                return ResourceManager.GetString("RetryTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run at System Startup 的本地化字符串。
        /// </summary>
        public static string RunAtSystemStartup {
            get {
                return ResourceManager.GetString("RunAtSystemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save configuration: {0} 的本地化字符串。
        /// </summary>
        public static string SaveConfigFailed {
            get {
                return ResourceManager.GetString("SaveConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save List 的本地化字符串。
        /// </summary>
        public static string SaveList {
            get {
                return ResourceManager.GetString("SaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll to top 的本地化字符串。
        /// </summary>
        public static string ScrollToTop {
            get {
                return ResourceManager.GetString("ScrollToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto scroll to top 的本地化字符串。
        /// </summary>
        public static string ScrollToTopOnReopen {
            get {
                return ResourceManager.GetString("ScrollToTopOnReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Account 的本地化字符串。
        /// </summary>
        public static string SelectAccount {
            get {
                return ResourceManager.GetString("SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Account Type 的本地化字符串。
        /// </summary>
        public static string SelectAccountType {
            get {
                return ResourceManager.GetString("SelectAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send notification after manually upload 的本地化字符串。
        /// </summary>
        public static string SendNotificationAfterManuallyUpload {
            get {
                return ResourceManager.GetString("SendNotificationAfterManuallyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send notification after updating local clipboard 的本地化字符串。
        /// </summary>
        public static string SendNotificationAfterUpdateLocalClipboard {
            get {
                return ResourceManager.GetString("SendNotificationAfterUpdateLocalClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Address 的本地化字符串。
        /// </summary>
        public static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full URL address of the WebDAV server 的本地化字符串。
        /// </summary>
        public static string ServerAddressDescription {
            get {
                return ResourceManager.GetString("ServerAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you want to sync the clipboard on this machine, please add an account and enable syncing on the &quot;Clipboard Syncing&quot; page 的本地化字符串。
        /// </summary>
        public static string ServerDescription {
            get {
                return ResourceManager.GetString("ServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server time differs significantly from local time. Please synchronize your system clock. 的本地化字符串。
        /// </summary>
        public static string ServerTimeError {
            get {
                return ResourceManager.GetString("ServerTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Sync Status 的本地化字符串。
        /// </summary>
        public static string ShowSyncStatus {
            get {
                return ResourceManager.GetString("ShowSyncStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local version v{0}. Lasted released version {1}. 的本地化字符串。
        /// </summary>
        public static string SoftwareUpdateInfo {
            get {
                return ResourceManager.GetString("SoftwareUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by Last Accessed 的本地化字符串。
        /// </summary>
        public static string SortByLastAccessed {
            get {
                return ResourceManager.GetString("SortByLastAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On/Off Built In Server 的本地化字符串。
        /// </summary>
        public static string SwitchBuiltInServer {
            get {
                return ResourceManager.GetString("SwitchBuiltInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On/Off Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string SwitchClipboardSyncing {
            get {
                return ResourceManager.GetString("SwitchClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On/Off Image Assistant 的本地化字符串。
        /// </summary>
        public static string SwitchImageAssistant {
            get {
                return ResourceManager.GetString("SwitchImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Off Built-In Server 的本地化字符串。
        /// </summary>
        public static string SwitchOffBuiltInServer {
            get {
                return ResourceManager.GetString("SwitchOffBuiltInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Off Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string SwitchOffClipboardSyncing {
            get {
                return ResourceManager.GetString("SwitchOffClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Off Image Assistant 的本地化字符串。
        /// </summary>
        public static string SwitchOffImageAssistant {
            get {
                return ResourceManager.GetString("SwitchOffImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On Built-In Server 的本地化字符串。
        /// </summary>
        public static string SwitchOnBuiltInServer {
            get {
                return ResourceManager.GetString("SwitchOnBuiltInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string SwitchOnClipboardSyncing {
            get {
                return ResourceManager.GetString("SwitchOnClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On Image Assistant 的本地化字符串。
        /// </summary>
        public static string SwitchOnImageAssistant {
            get {
                return ResourceManager.GetString("SwitchOnImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync Account 的本地化字符串。
        /// </summary>
        public static string SyncAccount {
            get {
                return ResourceManager.GetString("SyncAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync Content Control 的本地化字符串。
        /// </summary>
        public static string SyncContentControl {
            get {
                return ResourceManager.GetString("SyncContentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syncing 的本地化字符串。
        /// </summary>
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Operations 的本地化字符串。
        /// </summary>
        public static string SystemOperations {
            get {
                return ResourceManager.GetString("SystemOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Proxy 的本地化字符串。
        /// </summary>
        public static string SystemProxy {
            get {
                return ResourceManager.GetString("SystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Recommend 的本地化字符串。
        /// </summary>
        public static string SystemRecommend {
            get {
                return ResourceManager.GetString("SystemRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Style 的本地化字符串。
        /// </summary>
        public static string SystemStyle {
            get {
                return ResourceManager.GetString("SystemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temp Files Remain Days 的本地化字符串。
        /// </summary>
        public static string TempFileRemainDays {
            get {
                return ResourceManager.GetString("TempFileRemainDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test was cancelled. 的本地化字符串。
        /// </summary>
        public static string TestCancelled {
            get {
                return ResourceManager.GetString("TestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Connection 的本地化字符串。
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred while testing connection: {0} 的本地化字符串。
        /// </summary>
        public static string TestConnectionError {
            get {
                return ResourceManager.GetString("TestConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network request timeout in seconds 的本地化字符串。
        /// </summary>
        public static string TimeoutDescription {
            get {
                return ResourceManager.GetString("TimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout Period (sec) 的本地化字符串。
        /// </summary>
        public static string TimeoutPeriod {
            get {
                return ResourceManager.GetString("TimeoutPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout (seconds) 的本地化字符串。
        /// </summary>
        public static string TimeoutSeconds {
            get {
                return ResourceManager.GetString("TimeoutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 200 的本地化字符串。
        /// </summary>
        public static string TrayIconContextMenuMinWidth {
            get {
                return ResourceManager.GetString("TrayIconContextMenuMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trust Insecure HTTPS Certificates 的本地化字符串。
        /// </summary>
        public static string TrustInsecureCertificate {
            get {
                return ResourceManager.GetString("TrustInsecureCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to trust self-signed or invalid SSL certificates 的本地化字符串。
        /// </summary>
        public static string TrustInsecureCertificateDescription {
            get {
                return ResourceManager.GetString("TrustInsecureCertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to copy because of missing files 的本地化字符串。
        /// </summary>
        public static string UnableToCopyByMissingFile {
            get {
                return ResourceManager.GetString("UnableToCopyByMissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version {0} found, please update from {1} 的本地化字符串。
        /// </summary>
        public static string UpdateFrom3rdSrc {
            get {
                return ResourceManager.GetString("UpdateFrom3rdSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard Uploaded 的本地化字符串。
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed, tried {0} times, error message: {1} 的本地化字符串。
        /// </summary>
        public static string UploadFailedStatus {
            get {
                return ResourceManager.GetString("UploadFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed, tried {0} times, error message: timeout 的本地化字符串。
        /// </summary>
        public static string UploadFailedStatusTimeout {
            get {
                return ResourceManager.GetString("UploadFailedStatusTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading 的本地化字符串。
        /// </summary>
        public static string UploadingFile {
            get {
                return ResourceManager.GetString("UploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Once Immediately 的本地化字符串。
        /// </summary>
        public static string UploadOnce {
            get {
                return ResourceManager.GetString("UploadOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Service 的本地化字符串。
        /// </summary>
        public static string UploadService {
            get {
                return ResourceManager.GetString("UploadService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Warning 的本地化字符串。
        /// </summary>
        public static string UploadWarning {
            get {
                return ResourceManager.GetString("UploadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload without Content Control 的本地化字符串。
        /// </summary>
        public static string UploadWithoutFilter {
            get {
                return ResourceManager.GetString("UploadWithoutFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect to built-in server directly without configuration 的本地化字符串。
        /// </summary>
        public static string UseBuiltInServerDescription {
            get {
                return ResourceManager.GetString("UseBuiltInServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Nextcloud 的本地化字符串。
        /// </summary>
        public static string UseNextcloud {
            get {
                return ResourceManager.GetString("UseNextcloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Config Location 的本地化字符串。
        /// </summary>
        public static string UserConfigLocation {
            get {
                return ResourceManager.GetString("UserConfigLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username for logging into the WebDAV server 的本地化字符串。
        /// </summary>
        public static string UserNameDescription {
            get {
                return ResourceManager.GetString("UserNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or password can&apos;t be blank 的本地化字符串。
        /// </summary>
        public static string UsernameOrPasswordBlank {
            get {
                return ResourceManager.GetString("UsernameOrPasswordBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string UserNameTabRepeat {
            get {
                return ResourceManager.GetString("UserNameTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Built-In Server 的本地化字符串。
        /// </summary>
        public static string UseSelfHostServer {
            get {
                return ResourceManager.GetString("UseSelfHostServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White List 的本地化字符串。
        /// </summary>
        public static string WhiteList {
            get {
                return ResourceManager.GetString("WhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window topmost 的本地化字符串。
        /// </summary>
        public static string WindowTopmost {
            get {
                return ResourceManager.GetString("WindowTopmost", resourceCulture);
            }
        }
    }
}
