//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncClipboard.Core.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncClipboard.Core.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assistant 的本地化字符串。
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled 的本地化字符串。
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This change effects after restart 的本地化字符串。
        /// </summary>
        public static string ChangingLangInfo {
            get {
                return ResourceManager.GetString("ChangingLangInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for update…… 的本地化字符串。
        /// </summary>
        public static string CheckingUpdate {
            get {
                return ResourceManager.GetString("CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update for Beta Channel 的本地化字符串。
        /// </summary>
        public static string CheckUpdateForBetaChannel {
            get {
                return ResourceManager.GetString("CheckUpdateForBetaChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update on Startup 的本地化字符串。
        /// </summary>
        public static string CheckUpdateOnStartup {
            get {
                return ResourceManager.GetString("CheckUpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client General 的本地化字符串。
        /// </summary>
        public static string ClientGeneral {
            get {
                return ResourceManager.GetString("ClientGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard file updated 的本地化字符串。
        /// </summary>
        public static string ClipboardFileUpdated {
            get {
                return ResourceManager.GetString("ClipboardFileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard image updated 的本地化字符串。
        /// </summary>
        public static string ClipboardImageUpdated {
            get {
                return ResourceManager.GetString("ClipboardImageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string ClipboardSyncing {
            get {
                return ResourceManager.GetString("ClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard text updated 的本地化字符串。
        /// </summary>
        public static string ClipboardTextUpdated {
            get {
                return ResourceManager.GetString("ClipboardTextUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard updated 的本地化字符串。
        /// </summary>
        public static string ClipboardUpdated {
            get {
                return ResourceManager.GetString("ClipboardUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completely exit 的本地化字符串。
        /// </summary>
        public static string CompletelyExit {
            get {
                return ResourceManager.GetString("CompletelyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy And Upload 的本地化字符串。
        /// </summary>
        public static string CopyAndUpload {
            get {
                return ResourceManager.GetString("CopyAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy app data folder path to clipboard 的本地化字符串。
        /// </summary>
        public static string CopyAppDataFolderPath {
            get {
                return ResourceManager.GetString("CopyAppDataFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto detect 的本地化字符串。
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete server&apos;s temporary file automatically 的本地化字符串。
        /// </summary>
        public static string DeleteServerTemporaryFileAutoly {
            get {
                return ResourceManager.GetString("DeleteServerTemporaryFileAutoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnose 的本地化字符串。
        /// </summary>
        public static string Diagnose {
            get {
                return ResourceManager.GetString("Diagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnose Mode 的本地化字符串。
        /// </summary>
        public static string DiagnoseMode {
            get {
                return ResourceManager.GetString("DiagnoseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please download and install the icon font manually 的本地化字符串。
        /// </summary>
        public static string DownloadAndInstallIconFont {
            get {
                return ResourceManager.GetString("DownloadAndInstallIconFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download And Paste 的本地化字符串。
        /// </summary>
        public static string DownloadAndPaste {
            get {
                return ResourceManager.GetString("DownloadAndPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download file 的本地化字符串。
        /// </summary>
        public static string DownloadingFile {
            get {
                return ResourceManager.GetString("DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading web image 的本地化字符串。
        /// </summary>
        public static string DownloadingWebImage {
            get {
                return ResourceManager.GetString("DownloadingWebImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Once Immediately 的本地化字符串。
        /// </summary>
        public static string DownloadOnce {
            get {
                return ResourceManager.GetString("DownloadOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Service 的本地化字符串。
        /// </summary>
        public static string DownloadService {
            get {
                return ResourceManager.GetString("DownloadService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading status 的本地化字符串。
        /// </summary>
        public static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Web Image 的本地化字符串。
        /// </summary>
        public static string DownloadWebImage {
            get {
                return ResourceManager.GetString("DownloadWebImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download the original file and copy it after copying a image in browser 的本地化字符串。
        /// </summary>
        public static string DownloadWebImageDescription {
            get {
                return ResourceManager.GetString("DownloadWebImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Login Failed 的本地化字符串。
        /// </summary>
        public static string FailedToAuth {
            get {
                return ResourceManager.GetString("FailedToAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check update 的本地化字符串。
        /// </summary>
        public static string FailedToCheck {
            get {
                return ResourceManager.GetString("FailedToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download clipboard 的本地化字符串。
        /// </summary>
        public static string FailedToDownloadClipboard {
            get {
                return ResourceManager.GetString("FailedToDownloadClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to set 的本地化字符串。
        /// </summary>
        public static string FailedToSet {
            get {
                return ResourceManager.GetString("FailedToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to start server 的本地化字符串。
        /// </summary>
        public static string FailedToStartServer {
            get {
                return ResourceManager.GetString("FailedToStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to Upload:  的本地化字符串。
        /// </summary>
        public static string FailedToUpload {
            get {
                return ResourceManager.GetString("FailedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to parse version from Github 的本地化字符串。
        /// </summary>
        public static string FailToParseVersion {
            get {
                return ResourceManager.GetString("FailToParseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found new version 的本地化字符串。
        /// </summary>
        public static string FoundNewVersion {
            get {
                return ResourceManager.GetString("FoundNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Window on Startup 的本地化字符串。
        /// </summary>
        public static string HideOnStartup {
            get {
                return ResourceManager.GetString("HideOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys 的本地化字符串。
        /// </summary>
        public static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon Missing Detected 的本地化字符串。
        /// </summary>
        public static string IconMissingDetected {
            get {
                return ResourceManager.GetString("IconMissingDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Assistant 的本地化字符串。
        /// </summary>
        public static string ImageAssistant {
            get {
                return ResourceManager.GetString("ImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste image to a textbox directly after copying a image file from file system, and vice versa 的本地化字符串。
        /// </summary>
        public static string ImageAssistantDescription {
            get {
                return ResourceManager.GetString("ImageAssistantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Compatibility 的本地化字符串。
        /// </summary>
        public static string ImageCompatibility {
            get {
                return ResourceManager.GetString("ImageCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the transcoded temporary image file (jpg or gif) after copying a modern image file (heic, webp, etc.) 的本地化字符串。
        /// </summary>
        public static string ImageCompatibilityDescription {
            get {
                return ResourceManager.GetString("ImageCompatibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s the latest version 的本地化字符串。
        /// </summary>
        public static string ItsLatestVersion {
            get {
                return ResourceManager.GetString("ItsLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest released version 的本地化字符串。
        /// </summary>
        public static string LatestReleasedVersion {
            get {
                return ResourceManager.GetString("LatestReleasedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License 的本地化字符串。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local version 的本地化字符串。
        /// </summary>
        public static string LocalVersion {
            get {
                return ResourceManager.GetString("LocalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login with Browser 的本地化字符串。
        /// </summary>
        public static string LoginWithBrowser {
            get {
                return ResourceManager.GetString("LoginWithBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log path is null 的本地化字符串。
        /// </summary>
        public static string LogPathNull {
            get {
                return ResourceManager.GetString("LogPathNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Remain Days 的本地化字符串。
        /// </summary>
        public static string LogRemainDays {
            get {
                return ResourceManager.GetString("LogRemainDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max File Size to Upload (MB) 的本地化字符串。
        /// </summary>
        public static string MaxFileSizeToUpload {
            get {
                return ResourceManager.GetString("MaxFileSizeToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mixed Client Mode 的本地化字符串。
        /// </summary>
        public static string MixedClientMode {
            get {
                return ResourceManager.GetString("MixedClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off: Use standalone files to save clients&apos; clipboard information. 的本地化字符串。
        /// </summary>
        public static string MixedClientOffInfo {
            get {
                return ResourceManager.GetString("MixedClientOffInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On: When clients update/get clipboard infomation to/from this server, directly operate this machie&apos;s clipboard. So this machine&apos;s clipboard is shared forcely and with no delay. 的本地化字符串。
        /// </summary>
        public static string MixedClientOnInfo {
            get {
                return ResourceManager.GetString("MixedClientOnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Config File 的本地化字符串。
        /// </summary>
        public static string OpenConfigFile {
            get {
                return ResourceManager.GetString("OpenConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open App Data Folder 的本地化字符串。
        /// </summary>
        public static string OpenConfigFileFolder {
            get {
                return ResourceManager.GetString("OpenConfigFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open app data folder in Nautilus 的本地化字符串。
        /// </summary>
        public static string OpenDataFolderInNautilus {
            get {
                return ResourceManager.GetString("OpenDataFolderInNautilus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string OpenDownloadPage {
            get {
                return ResourceManager.GetString("OpenDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in browser 的本地化字符串。
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Main UI 的本地化字符串。
        /// </summary>
        public static string OpenMainUI {
            get {
                return ResourceManager.GetString("OpenMainUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Source Dependencies 的本地化字符串。
        /// </summary>
        public static string OpenSourceDependencies {
            get {
                return ResourceManager.GetString("OpenSourceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string PasswordTabRepeat {
            get {
                return ResourceManager.GetString("PasswordTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port range is 1~65535 的本地化字符串。
        /// </summary>
        public static string PortRangeIs {
            get {
                return ResourceManager.GetString("PortRangeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string PortTabRepeat {
            get {
                return ResourceManager.GetString("PortTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing 的本地化字符串。
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Interval (sec) 的本地化字符串。
        /// </summary>
        public static string QueryInterval {
            get {
                return ResourceManager.GetString("QueryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload Config File 的本地化字符串。
        /// </summary>
        public static string ReloadConfigFile {
            get {
                return ResourceManager.GetString("ReloadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to Default 的本地化字符串。
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run at System Startup 的本地化字符串。
        /// </summary>
        public static string RunAtSystemStartup {
            get {
                return ResourceManager.GetString("RunAtSystemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send notification after manually upload 的本地化字符串。
        /// </summary>
        public static string SendNotificationAfterManuallyUpload {
            get {
                return ResourceManager.GetString("SendNotificationAfterManuallyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send notification after updating local clipboard 的本地化字符串。
        /// </summary>
        public static string SendNotificationAfterUpdateLocalClipboard {
            get {
                return ResourceManager.GetString("SendNotificationAfterUpdateLocalClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one server is needed in entire sync network 的本地化字符串。
        /// </summary>
        public static string ServerDescription {
            get {
                return ResourceManager.GetString("ServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Home Page 的本地化字符串。
        /// </summary>
        public static string SoftwareHomePage {
            get {
                return ResourceManager.GetString("SoftwareHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local version v{0}. Lasted released version {1}. 的本地化字符串。
        /// </summary>
        public static string SoftwareUpdateInfo {
            get {
                return ResourceManager.GetString("SoftwareUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On/Off Built In Server 的本地化字符串。
        /// </summary>
        public static string SwitchBuiltInServer {
            get {
                return ResourceManager.GetString("SwitchBuiltInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On/Off Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string SwitchClipboardSyncing {
            get {
                return ResourceManager.GetString("SwitchClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On/Off Image Assistant 的本地化字符串。
        /// </summary>
        public static string SwitchImageAssistant {
            get {
                return ResourceManager.GetString("SwitchImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On/Off Mixed Client Mode 的本地化字符串。
        /// </summary>
        public static string SwitchMixedClientMode {
            get {
                return ResourceManager.GetString("SwitchMixedClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Off Built-In Server 的本地化字符串。
        /// </summary>
        public static string SwitchOffBuiltInServer {
            get {
                return ResourceManager.GetString("SwitchOffBuiltInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Off Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string SwitchOffClipboardSyncing {
            get {
                return ResourceManager.GetString("SwitchOffClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Off Image Assistant 的本地化字符串。
        /// </summary>
        public static string SwitchOffImageAssistant {
            get {
                return ResourceManager.GetString("SwitchOffImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Off Mixed Client Mode 的本地化字符串。
        /// </summary>
        public static string SwitchOffMixedClientMode {
            get {
                return ResourceManager.GetString("SwitchOffMixedClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On Built-In Server 的本地化字符串。
        /// </summary>
        public static string SwitchOnBuiltInServer {
            get {
                return ResourceManager.GetString("SwitchOnBuiltInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string SwitchOnClipboardSyncing {
            get {
                return ResourceManager.GetString("SwitchOnClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On Image Assistant 的本地化字符串。
        /// </summary>
        public static string SwitchOnImageAssistant {
            get {
                return ResourceManager.GetString("SwitchOnImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch On Mixed Client Mode 的本地化字符串。
        /// </summary>
        public static string SwitchOnMixedClientMode {
            get {
                return ResourceManager.GetString("SwitchOnMixedClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syncing 的本地化字符串。
        /// </summary>
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Operations 的本地化字符串。
        /// </summary>
        public static string SystemOperations {
            get {
                return ResourceManager.GetString("SystemOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Style 的本地化字符串。
        /// </summary>
        public static string SystemStyle {
            get {
                return ResourceManager.GetString("SystemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout Period (sec) 的本地化字符串。
        /// </summary>
        public static string TimeoutPeriod {
            get {
                return ResourceManager.GetString("TimeoutPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 200 的本地化字符串。
        /// </summary>
        public static string TrayIconContextMenuMinWidth {
            get {
                return ResourceManager.GetString("TrayIconContextMenuMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trust Insecure HTTPS Certificates 的本地化字符串。
        /// </summary>
        public static string TrustInsecureCertificate {
            get {
                return ResourceManager.GetString("TrustInsecureCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard Uploaded 的本地化字符串。
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed, tried {0} times, error message: {1} 的本地化字符串。
        /// </summary>
        public static string UploadFailedStatus {
            get {
                return ResourceManager.GetString("UploadFailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed, tried {0} times, error message: timeout 的本地化字符串。
        /// </summary>
        public static string UploadFailedStatusTimeout {
            get {
                return ResourceManager.GetString("UploadFailedStatusTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Once Immediately 的本地化字符串。
        /// </summary>
        public static string UploadOnce {
            get {
                return ResourceManager.GetString("UploadOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Service 的本地化字符串。
        /// </summary>
        public static string UploadService {
            get {
                return ResourceManager.GetString("UploadService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect to built-in server directly without configuration 的本地化字符串。
        /// </summary>
        public static string UseBuiltInServerDescription {
            get {
                return ResourceManager.GetString("UseBuiltInServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Nextcloud 的本地化字符串。
        /// </summary>
        public static string UseNextcloud {
            get {
                return ResourceManager.GetString("UseNextcloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or password can&apos;t be blank 的本地化字符串。
        /// </summary>
        public static string UsernameOrPasswordBlank {
            get {
                return ResourceManager.GetString("UsernameOrPasswordBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string UserNameTabRepeat {
            get {
                return ResourceManager.GetString("UserNameTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Built-In Server 的本地化字符串。
        /// </summary>
        public static string UseSelfHostServer {
            get {
                return ResourceManager.GetString("UseSelfHostServer", resourceCulture);
            }
        }
    }
}
