<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../SyncClipboard.Updater.Core/Updater.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
</Project>
