//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncClipboard.Core.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncClipboard.Core.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assistant 的本地化字符串。
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This change effects after restart 的本地化字符串。
        /// </summary>
        public static string ChangingLangInfo {
            get {
                return ResourceManager.GetString("ChangingLangInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update On Startup 的本地化字符串。
        /// </summary>
        public static string CheckUpdateOnStartup {
            get {
                return ResourceManager.GetString("CheckUpdateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client General 的本地化字符串。
        /// </summary>
        public static string ClientGeneral {
            get {
                return ResourceManager.GetString("ClientGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard Syncing 的本地化字符串。
        /// </summary>
        public static string ClipboardSyncing {
            get {
                return ResourceManager.GetString("ClipboardSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Detect 的本地化字符串。
        /// </summary>
        public static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Server&apos;s Template File Autoly 的本地化字符串。
        /// </summary>
        public static string DeleteServerTemplateFileAutoly {
            get {
                return ResourceManager.GetString("DeleteServerTemplateFileAutoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Service 的本地化字符串。
        /// </summary>
        public static string DownloadService {
            get {
                return ResourceManager.GetString("DownloadService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Web Image 的本地化字符串。
        /// </summary>
        public static string DownloadWebImage {
            get {
                return ResourceManager.GetString("DownloadWebImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download the original file and copy it after copying a image in browser 的本地化字符串。
        /// </summary>
        public static string DownloadWebImageDescription {
            get {
                return ResourceManager.GetString("DownloadWebImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Assistant 的本地化字符串。
        /// </summary>
        public static string ImageAssistant {
            get {
                return ResourceManager.GetString("ImageAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste image to a textbox directly after copying a image file from file system, and vice versa 的本地化字符串。
        /// </summary>
        public static string ImageAssistantDescription {
            get {
                return ResourceManager.GetString("ImageAssistantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Compatibility 的本地化字符串。
        /// </summary>
        public static string ImageCompatibility {
            get {
                return ResourceManager.GetString("ImageCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the transcoded temporary image file (jpg or gif) after copying a modern image file (heic, webp, etc.) 的本地化字符串。
        /// </summary>
        public static string ImageCompatibilityDescription {
            get {
                return ResourceManager.GetString("ImageCompatibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login With Browser 的本地化字符串。
        /// </summary>
        public static string LoginWithBrowser {
            get {
                return ResourceManager.GetString("LoginWithBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max File Size To Upload (MB) 的本地化字符串。
        /// </summary>
        public static string MaxFileSizeToUpload {
            get {
                return ResourceManager.GetString("MaxFileSizeToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mixed Client Mode 的本地化字符串。
        /// </summary>
        public static string MixedClientMode {
            get {
                return ResourceManager.GetString("MixedClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off: Use standalone files to save clients&apos; clipboard information. 的本地化字符串。
        /// </summary>
        public static string MixedClientOffInfo {
            get {
                return ResourceManager.GetString("MixedClientOffInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On: When clients update/get clipboard info from this server, directly operate this machie&apos;s clipboard. So this machine&apos;s clipboard is shared forcely and with no delay. 的本地化字符串。
        /// </summary>
        public static string MixedClientOnInfo {
            get {
                return ResourceManager.GetString("MixedClientOnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Source Dependencies 的本地化字符串。
        /// </summary>
        public static string OpenSourceDependencies {
            get {
                return ResourceManager.GetString("OpenSourceDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string PasswordTabRepeat {
            get {
                return ResourceManager.GetString("PasswordTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string PortTabRepeat {
            get {
                return ResourceManager.GetString("PortTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Interval (sec) 的本地化字符串。
        /// </summary>
        public static string QueryInterval {
            get {
                return ResourceManager.GetString("QueryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Notification After Update Local Clipboard 的本地化字符串。
        /// </summary>
        public static string SendNotificationAfterUpdateLocalClipboard {
            get {
                return ResourceManager.GetString("SendNotificationAfterUpdateLocalClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self-Host Server 的本地化字符串。
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Home Page 的本地化字符串。
        /// </summary>
        public static string SoftwareHomePage {
            get {
                return ResourceManager.GetString("SoftwareHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syncing 的本地化字符串。
        /// </summary>
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout Period (sec) 的本地化字符串。
        /// </summary>
        public static string TimeoutPeriod {
            get {
                return ResourceManager.GetString("TimeoutPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Service 的本地化字符串。
        /// </summary>
        public static string UploadService {
            get {
                return ResourceManager.GetString("UploadService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Nextcloud 的本地化字符串。
        /// </summary>
        public static string UseNextcloud {
            get {
                return ResourceManager.GetString("UseNextcloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string UserNameTabRepeat {
            get {
                return ResourceManager.GetString("UserNameTabRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Self-Host Server 的本地化字符串。
        /// </summary>
        public static string UseSelfHostServer {
            get {
                return ResourceManager.GetString("UseSelfHostServer", resourceCulture);
            }
        }
    }
}
