name: build-pr

on:
  pull_request:

jobs:
  code-style:
    uses: ./.github/workflows/code-style.yml

  core-test:
    uses: ./.github/workflows/core-test.yml

  prebuild:
    uses: ./.github/workflows/prebuild.yml
    with:
      checkout-repo: ${{ github.repository }}
      checkout-ref: ${{ github.ref }}

  build-win:
    uses: ./.github/workflows/win-package.yml
    needs: prebuild

  build-server:
    uses: ./.github/workflows/server-build.yml

  build-linux:
    uses: ./.github/workflows/linux-package.yml
    needs: prebuild
    with:
      checkout-repo: ${{ github.repository }}
      checkout-ref: ${{ github.ref }}
    
  build-mac:
    uses: ./.github/workflows/mac-package.yml
    needs: prebuild
    with:
      checkout-repo: ${{ github.repository }}
      checkout-ref: ${{ github.ref }}

  windows-test:
    needs: build-win
    uses: ./.github/workflows/windows-test.yml

  macos-test:
    needs: build-mac
    uses: ./.github/workflows/macos-test.yml

  linux-test:
    needs: build-linux
    uses: ./.github/workflows/linux-test.yml
