name: code-style

on:
  workflow_call:

jobs:
  check:
    runs-on: macos-14  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Install dependencies
      working-directory: ./src
      run: |
        dotnet workload install macos
        dotnet workload restore
        dotnet restore

    - name: Check code style
      working-directory: ./src
      run: |
        dotnet format --verify-no-changes --no-restore

    - name: Check code style info
      continue-on-error: true
      working-directory: ./src
      run: |
        dotnet format --verify-no-changes --severity info --no-restore