name: linux-package

on:
  workflow_call:
    inputs:
      checkout-repo:
        required: true
        type: string
      checkout-ref:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/linux-compile.yml
    with:
      checkout-repo: ${{ inputs.checkout-repo }}
      checkout-ref: ${{ inputs.checkout-ref }}

  package-linux:
    strategy:
      matrix:
        cpu: [x64, arm64]
        type: [self-contained, no-self-contained]
        package-type: [AppImage, rpm, deb]
        include:
          - package-type: AppImage
            cpu: x64
            package-head: SyncClipboard-
            package-tail: .x86_64
          - package-type: rpm
            cpu: x64
            package-head: syncclipboard_
            package-tail: .x86_64
          - package-type: deb
            cpu: x64
            package-head: syncclipboard_
            package-tail: _amd64
          - package-type: AppImage
            cpu: arm64
            package-head: SyncClipboard-
            package-tail: .aarch64
          - package-type: deb
            cpu: arm64
            package-head: syncclipboard_
            package-tail: _arm64
          # - package-type: rpm
          #   cpu: arm64
          #   package-head: syncclipboard_
          #   package-tail: .arm64
          - type: self-contained
            package-dotnet-runtime: ''
          - type: no-self-contained
            package-dotnet-runtime: '_no-dotnet-runtime'
        exclude: # rpmbuild arm64 failed https://github.com/kuiperzone/PupNet-Deploy/issues/3
          - package-type: rpm
            cpu: arm64

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.checkout-repo }}
          ref: ${{ inputs.checkout-ref }}

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Download last-job-built artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-${{ matrix.cpu }}-${{ matrix.type }}
          path: linux-bin/

      - name: Download last-job-built change log
        uses: actions/download-artifact@v4
        with:
          name: feature

      - name: Install pupnet and denpendencies
        run: |
          dotnet tool install -g KuiperZone.PupNet
          sudo apt install libfuse2

      - name: Package
        run: >
          chmod +x package.sh &&
          ./package.sh
          -k ${{ matrix.package-type }}
          -r linux-${{ matrix.cpu }}
          -s ../../linux-bin/
        working-directory: ./build/linux

      - name: rename package
        run: >
          mv ${{ matrix.package-head }}*-*${{ matrix.package-tail }}.${{ matrix.package-type }}
          SyncClipboard_linux_${{ matrix.cpu }}${{ matrix.package-dotnet-runtime }}.${{ matrix.package-type }}
        working-directory: ./build/linux/output

      - name: Upload build artifacts ${{ matrix.type }} ${{ matrix.package-type }}
        uses: actions/upload-artifact@v4
        with:
          name: SyncClipboard_linux_${{ matrix.cpu }}${{ matrix.package-dotnet-runtime }}.${{ matrix.package-type }}
          path: build/linux/output/SyncClipboard_linux_${{ matrix.cpu }}${{ matrix.package-dotnet-runtime }}.${{ matrix.package-type }}