name: linux-compile

on:
  workflow_call:
    inputs:
      checkout-repo:
        required: true
        type: string
      checkout-ref:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        cpu: [x64, arm64]
        type: [self-contained, no-self-contained]
        include:
           - cpu: x64
             runner: ubuntu-24.04
           - cpu: arm64
             runner: ubuntu-24.04-arm
           - type: self-contained
             ifSelf: "true"
           - type: no-self-contained
             ifSelf: "false"

    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: ${{ inputs.checkout-repo }}
        ref: ${{ inputs.checkout-ref }}

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.302

    - name: Show selected SDK
      run: dotnet --info

    - name: Install native toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y clang zlib1g-dev

    - name: Build linux-${{ matrix.cpu }}-${{ matrix.type }}
      run: >-
        dotnet publish src/SyncClipboard.Desktop.Default/SyncClipboard.Desktop.Default.csproj
        -f net10.0 -r linux-${{ matrix.cpu }} -c Release
        -p:Platform=${{ matrix.cpu }} --self-contained ${{ matrix.ifSelf }}
        -o linux-${{ matrix.cpu }}-${{ matrix.type }}

    - name: Upload linux-${{ matrix.cpu }}-${{ matrix.type }}
      uses: actions/upload-artifact@v7
      with:
        name: linux-${{ matrix.cpu }}-${{ matrix.type }}
        path: linux-${{ matrix.cpu }}-${{ matrix.type }}/
