name: release-formal

permissions:
  contents: write

on:
  workflow_call:

jobs:
  release-formal:
    runs-on: windows-latest
    steps:
      - name: Download last-job-built change log
        uses: actions/download-artifact@v4
        with:
          name: feature

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          allowUpdates: true
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          bodyFile: feature.txt